Exclude Archived repositories and Mesages starting with @UbiquityOS
ubiquity-os-marketplace/command-ask pull request #46
Opened 2024-12-23 19:45 UTC by Sadaf-A

Resolves #7

2024-12-29 06:48 UTC, Sadaf-A commented
@0x4007 could I please get a review on this?

2024-12-30 03:40 UTC, Sadaf-A commented
@rndquu could you please review this PR?
Thank You

2024-12-31 10:35 UTC, rndquu commented
> @rndquu could you please review this PR? Thank You

Could you provide QA links of how it works for `@UbiquityOS`, archived and none-archived repositories?

2024-12-31 10:37 UTC, Sadaf-A commented
> > @rndquu could you please review this PR? Thank You
> 
> Could you provide QA links of how it works for `@UbiquityOS`, archived and none-archived repositories?

Hey, is there a guide available for how to QA?

2024-12-31 10:43 UTC, rndquu commented
> > > @rndquu could you please review this PR? Thank You
> > 
> > 
> > Could you provide QA links of how it works for `@UbiquityOS`, archived and none-archived repositories?
> 
> Hey, is there a guide available for how to QA?

Just post URL links in the comments to prove that the feature works and nothing is broken

2024-12-31 14:14 UTC, Sadaf-A commented
@UbiqityOS hi

2024-12-31 14:15 UTC, Sadaf-A commented
@UbiquityOS hi

2024-12-31 14:17 UTC, Sadaf-A commented
/ask hi what is the name of this repo?

2025-01-01 06:46 UTC, Sadaf-A commented
> > > > @rndquu could you please review this PR? Thank You
> > > 
> > > 
> > > Could you provide QA links of how it works for `@UbiquityOS`, archived and none-archived repositories?
> > 
> > Hey, is there a guide available for how to QA?
> 
> Just post URL links in the comments to prove that the feature works and nothing is broken

Hey, where should I post the comment?

2025-01-01 13:27 UTC, rndquu commented
> > > > > @rndquu could you please review this PR? Thank You
> > > > 
> > > > 
> > > > Could you provide QA links of how it works for `@UbiquityOS`, archived and none-archived repositories?
> > > 
> > > 
> > > Hey, is there a guide available for how to QA?
> > 
> > 
> > Just post URL links in the comments to prove that the feature works and nothing is broken
> 
> Hey, where should I post the comment?

In the PR description

2025-01-01 14:01 UTC, Sadaf-A commented
> > > > > > @rndquu could you please review this PR? Thank You
> > > > > 
> > > > > 
> > > > > Could you provide QA links of how it works for `@UbiquityOS`, archived and none-archived repositories?
> > > > 
> > > > 
> > > > Hey, is there a guide available for how to QA?
> > > 
> > > 
> > > Just post URL links in the comments to prove that the feature works and nothing is broken
> > 
> > Hey, where should I post the comment?
> 
> In the PR description

So this PR is using the same code that I pushed?

2025-01-01 14:03 UTC, Sadaf-A commented
@UbiquityOS testing

2025-01-01 14:03 UTC, Sadaf-A commented
/ask testing

2025-01-01 14:06 UTC, Sadaf-A commented
@rndquu is the /ask command deprecated?

2025-01-01 14:07 UTC, Sadaf-A commented
/ask what is this repository's name?

2025-01-01 14:38 UTC, Sadaf-A commented
@UbiquityOS testing

2025-01-01 14:42 UTC, Sadaf-A commented
@rndquu how do I check for archived repo?

2025-01-02 02:57 UTC, Sadaf-A commented
@rndquu is this the right way?

2025-01-02 02:57 UTC, Sadaf-A commented
/ask how do I do QA for this repo?

2025-01-02 16:43 UTC, Sadaf-A commented
how do I test it after deploying using wrangler?

2025-01-03 14:00 UTC, Sadaf-A commented
@rndquu hey could you please confirm if this is the right way to do QA?

2025-01-03 18:23 UTC, whilefoo requested changes

2025-01-03 18:23 UTC, whilefoo commented on src/handlers/ask-llm.ts
> +  }
I think @0x4007 meant that comments that start with @UbiquityOS should not be included in the LLM context

2025-01-03 18:26 UTC, Sadaf-A commented on src/handlers/ask-llm.ts
> +  }
Got it, I will fix this could you please guide me on how to do QA for this repo?

2025-01-04 07:55 UTC, rndquu commented
> @rndquu hey could you please confirm if this is the right way to do QA?

Post URLs from your own repository which show that the feature works as expected for:
- `@UbiquityOS`, 
- archived repositories
- none-archived repositories

2025-01-04 09:02 UTC, Sadaf-A commented
> > @rndquu hey could you please confirm if this is the right way to do QA?
> 
> Post URLs from your own repository which show that the feature works as expected for:
> 
> * `@UbiquityOS`,
> * archived repositories
> * none-archived repositories

I don't understand should I comment in my fork after creating an issue or something else?

2025-01-04 09:47 UTC, rndquu commented
> > > @rndquu hey could you please confirm if this is the right way to do QA?
> > 
> > 
> > Post URLs from your own repository which show that the feature works as expected for:
> > 
> > * `@UbiquityOS`,
> > * archived repositories
> > * none-archived repositories
> 
> I don't understand should I comment in my fork after creating an issue like [this](https://github.com/Sadaf-A/command-ask/issues/1) or something else? Could you please elaborate a little more on how to set things up as this is my first time contributing to this repo. Thank You

Create a github issue in your fork, check how it works in your fork, post URLs to relevant issue which shows how the feature works in comments in the current github issue.

2025-01-04 09:50 UTC, Sadaf-A commented
> > > > @rndquu hey could you please confirm if this is the right way to do QA?
> > > 
> > > 
> > > Post URLs from your own repository which show that the feature works as expected for:
> > > 
> > > * `@UbiquityOS`,
> > > * archived repositories
> > > * none-archived repositories
> > 
> > I don't understand should I comment in my fork after creating an issue like [this](https://github.com/Sadaf-A/command-ask/issues/1) or something else? Could you please elaborate a little more on how to set things up as this is my first time contributing to this repo. Thank You
> 
> Create a github issue in your fork, check how it works in your fork, post URLs to relevant issue which shows how the feature works in comments in the current github issue.

Thanks. Am I missing something cause there are no replies.

2025-01-27 07:34 UTC, closed without merging